project_id = "ojnayvmppwpbdcsddpaw"

[auth.email.template.confirmation]
subject = "Confirme seu cadastro no Spatioo"
content_path = "./supabase/templates/confirmation.html"

[functions.booking-accept]
[functions.booking-reject]
[functions.booking-confirm-arrival]
[functions.booking-confirm-departure]
[functions.expire-bookings]
verify_jwt = false