// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrpozzdzwvbmxseuntyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxycG96emR6d3ZibXhzZXVudHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDY5ODQsImV4cCI6MjA1ODUyMjk4NH0.prFjtzpLYYgF_zZLdhRU5LoUY7805XtnTio5usWwWmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);